// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Snoozeland")>]
[<assembly: AssemblyProductAttribute("Snoozeland")>]
[<assembly: AssemblyDescriptionAttribute("snoozeland room scene controller for raspberry pi written in F#")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Snoozeland"
    let [<Literal>] AssemblyProduct = "Snoozeland"
    let [<Literal>] AssemblyDescription = "snoozeland room scene controller for raspberry pi written in F#"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
